version: '3'

services:
  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_USER=reactmed
      - POSTGRES_PASSWORD=reactmed95root
      - POSTGRES_DB=reactmed
    volumes:
      - postgres_data:/var/lib/postgresl/data/
    expose:
      - "5432"
  web:
    build: .
    command: python /code/manage.py migrate
    command: python /code/manage.py clear_models
    command: python /code/manage.py loaddata /code/apps/core/fixtures/users.json
    command: python /code/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: